# Generated by Django 4.0.5 on 2022-06-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
